#!/bin/bash

echo "📁 Current Volume Mounts Configuration"
echo ""
echo "FRONTEND (Vite with HMR):"
echo "  ✓ frontend/src → /app/src (read-only)"
echo "  ✓ frontend/index.html → /app/index.html (read-only)"
echo "  ✓ frontend/vite.config.js → /app/vite.config.js (read-only)"
echo "  ℹ /app/node_modules (container-only, not overridden)"
echo ""
echo "BACKEND (Flask with auto-reload):"
echo "  ✓ backend/app.py → /app/app.py (read-only)"
echo "  ✓ backend/.env → /app/.env (read-only)"
echo ""
echo "NGINX:"
echo "  ✓ backend/nginx.conf → /etc/nginx/nginx.conf (read-only)"
echo "  ✓ certs/ → /etc/nginx/certs (read-only)"
echo ""
echo "Hot Reload Behavior:"
echo "  • Frontend: Instant updates via Vite HMR"
echo "  • Backend: Auto-restart on file change (~2-3s)"
echo "  • Nginx: Manual restart required"
echo ""
